### ISSUE TITLE
Null pointer exception on disabling animation

### ISSUE THREAD

**Issue by rahul860366** [ittianyu/BottomNavigationViewEx#110]
I am trying to disable all the animations, and getting a null point exception. Please find the stacktarace below.

```
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
        at com.ittianyu.bottomnavigationviewex.BottomNavigationViewEx.getBottomNavigationItemViews(BottomNavigationViewEx.java:569)
        at com.ittianyu.bottomnavigationviewex.BottomNavigationViewEx.enableItemShiftingMode(BottomNavigationViewEx.java:430)
        at dev.whaabaam.com.ui.home.HomeActivity.initBottomNav(HomeActivity.java:63)
        at dev.whaabaam.com.ui.home.HomeActivity.onCreate(HomeActivity.java:28)
```

**Comment by truongnmt** [comment]
Related: https://github.com/ittianyu/BottomNavigationViewEx/issues/108

**Comment by fairytale110** [comment]
I have resolved in my issues #118

**Comment by truongnmt** [comment]
@fairytale110 to be honest, I'm still confuse after seeing your issues #118 .
Can you explain for detail a little bit? For example to disable animation?
Thanks a lot!

**Comment by fairytale110** [comment]
@truongnmt 
It all  because BottomNavigationViewEx extends BottomNavigationView，But there are some deferents when your project‘s  compileSdkVersion >= 25，

BottomNavigationView 里面的大部分成员名称都改变了，例如对象名称都不再是字母m开始等，
我直接在BottomNavigationViewEx.java文件里面搜索“ getField”和“ setField”，找到所有调用都地方，修改方法参数“String fieldName”的值，
具体地，进入方法参数“Class targetClass”对应的源码，找到“fieldName”对应的对象，就可以找到正确的对象名称，

I am Chinese, my English is not very good, the content is translated by Google.
Most of the member names in BottomNavigationView have changed, for example, the object name is no longer the beginning of the letter m, etc.
I searched for "getField" and "setField" directly in the BottomNavigationViewEx.java file, found all the calls, and modified the value of the method parameter "String fieldName".
Specifically, enter the source code corresponding to the method parameter "Class targetClass", find the object corresponding to "fieldName", and you can find the correct object name.

**Comment by truongnmt** [comment]
@fairytale110 Thanks for your response! That's enough for me! ^^

**Comment by fairytale110** [comment]
@truongnmt 不客气，我也是昨晚研究了一晚上找到解决方案的。

**Comment by Abraham1999** [comment]
Please I don't know how to solve this issue
can you show me exactly how to solve it

**Comment by ubuntudroid** [comment]
As there still seems to be some confusion: you can simply use the fix on our fork.

```
implementation 'com.github.stanwood:BottomNavigationViewEx:41e335d'
```

@fairytale110 do you want a PR with that fix? Seems something similar has already been merged in an earlier PR, but has since somehow disappeared from master.

**Comment by ittianyu** [comment]
I am sorry to be late. Please use version 2.0.0 if support lib >= 28. 
Version 27 is abandoned.
For AndroidX, please add config into `gradle.properties`
```
android.useAndroidX=true
android.enableJetifier=true
```
